# Generated by Django 5.2.5 on 2025-09-16 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='recovery_phrase_hash',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='user',
            name='totp_secret',
            field=models.CharField(max_length=32, unique=True, verbose_name='TOTP secret'),
        ),
    ]
