# Generated by Django 5.2.5 on 2025-09-02 04:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=300)),
                ('author', models.CharField(max_length=150)),
                ('publish_date', models.DateField()),
                ('link', models.URLField()),
                ('suggested_reading_time', models.IntegerField()),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'videos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VideoProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.FloatField(default=0.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('video_id', models.ForeignKey(db_column='video_id', on_delete=django.db.models.deletion.CASCADE, to='videos.video')),
            ],
            options={
                'db_table': 'video_progress',
                'indexes': [models.Index(fields=['user_id'], name='video_progr_user_id_b8bfb1_idx'), models.Index(fields=['video_id'], name='video_progr_video_i_d13948_idx')],
                'unique_together': {('user_id', 'video_id')},
            },
        ),
    ]
