# Generated by Django 5.2.5 on 2025-09-21 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoprogress',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
