# Generated by Django 5.2.5 on 2025-09-20 05:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_user_recovery_phrase_hash_alter_user_totp_secret'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('requirement', models.IntegerField()),
                ('description', models.TextField()),
                ('icon_path', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'badge',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PrivacySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_score', models.BooleanField(default=True)),
                ('show_level', models.BooleanField(default=True)),
                ('show_badges', models.BooleanField(default=True)),
                ('show_achievements', models.BooleanField(default=True)),
                ('allow_public_ranking', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'privacy_setting',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RewardPoint',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('points_awarded', models.IntegerField()),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'reward_point',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TaskLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_awarded', models.IntegerField()),
                ('completed_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'task_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('invite_code', models.CharField(max_length=36, unique=True)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'teams',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TeamInvite',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_used', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'team_invite',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TeamMembership',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(default='member', max_length=20)),
                ('joined_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'team_membership',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserStats',
            fields=[
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='userstats', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('points', models.IntegerField(default=0)),
                ('challenge_level', models.IntegerField(default=1)),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'user_stats',
                'managed': False,
            },
        ),
    ]
