# Generated by Django 5.2.5 on 2025-09-01 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlacklistedDomains',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('registry_id', models.IntegerField()),
                ('domain', models.CharField(max_length=255)),
                ('date_added', models.DateField(blank=True, null=True)),
                ('date_removed', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'domains',
                'managed': False,
            },
        ),
    ]
