# Generated by Django 5.2.5 on 2025-09-16 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_article_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='article',
            table='articles',
        ),
    ]
