# Generated by Django 5.2.5 on 2025-09-17 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_article_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'managed': True},
        ),
    ]
