# Generated by Django 5.2.5 on 2025-09-01 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=36)),
                ('total_questions', models.IntegerField()),
                ('correct_count', models.IntegerField(default=0)),
                ('accuracy_pct', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'quiz_attempts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('question_text', models.TextField(blank=True, null=True)),
                ('option_a', models.TextField(blank=True, null=True)),
                ('option_b', models.TextField(blank=True, null=True)),
                ('option_c', models.TextField(blank=True, null=True)),
                ('option_d', models.TextField(blank=True, null=True)),
                ('option_e', models.TextField(blank=True, null=True)),
                ('correct_answer', models.CharField(blank=True, max_length=10, null=True)),
                ('explanation', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cyber_tests',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QuizQuestionAttempt',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=36)),
                ('question_id', models.BigIntegerField()),
                ('chosen_answer', models.CharField(max_length=10)),
                ('is_correct', models.BooleanField()),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('attempt_id', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'answers',
                'managed': False,
            },
        ),
    ]
