# Generated by Django 5.2.5 on 2025-09-21 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='quizquestion',
            table='quiz_new',
        ),
        migrations.AlterModelTable(
            name='quizquestionattempt',
            table='answers_new',
        ),
    ]
