# Generated by Django 5.2.5 on 2025-09-09 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialLoss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('median_type', models.CharField(max_length=255)),
                ('cybercrime', models.CharField(max_length=255)),
                ('value', models.IntegerField()),
                ('tooltip', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'financial_losses',
            },
        ),
        migrations.CreateModel(
            name='OnlineBehaviour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tab', models.CharField(max_length=100)),
                ('behaviour_type', models.CharField(max_length=255)),
                ('variable', models.CharField(max_length=255)),
                ('tech_level', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(max_length=20)),
                ('age', models.CharField(max_length=50)),
                ('sme_status', models.CharField(blank=True, max_length=100, null=True)),
                ('adjusted_2023', models.FloatField(blank=True, null=True)),
                ('adjusted_2024', models.FloatField(blank=True, null=True)),
                ('significant_diff', models.BooleanField(null=True)),
            ],
            options={
                'db_table': 'online_behaviours',
            },
        ),
        migrations.CreateModel(
            name='Victimisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tab', models.CharField(max_length=100)),
                ('main_type', models.CharField(max_length=255)),
                ('subcategory', models.CharField(blank=True, max_length=255, null=True)),
                ('incident_type', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(max_length=20)),
                ('age', models.CharField(max_length=50)),
                ('sme_status', models.CharField(max_length=100)),
                ('prevalence_2024', models.FloatField()),
                ('adjusted_2023', models.FloatField(blank=True, null=True)),
                ('adjusted_2024', models.FloatField(blank=True, null=True)),
                ('significant_diff', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'victimisation',
            },
        ),
    ]
